name: "MultiRepo Workspace"
# git pull || hub sync
pull: hub
port: 8080
repos:
  ui:
    git: "git@github.com:MultiRepo-Workspace/ui.git"
    branch: "develop"
  cli:
    git: "git@github.com:MultiRepo-Workspace/cli.git"
    branch: "develop"
