name: "MultiRepo Workspace"
# git pull || hub sync
pull: hub
port: 8080
repos:
  - path: "ui"
    git: "git@github.com:MultiRepo-Workspace/ui.git"
    branch: "develop"
  - path: "cli"
    git: "git@github.com:MultiRepo-Workspace/cli.git"
    branch: "develop"
